# Generated by Django 4.1.2 on 2022-10-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(default='', max_length=255)),
                ('sub_category', models.CharField(default='', max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
